//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGroupe2.ServiceMetier {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMetier.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MetierRvMedical.CompositeType GetDataUsingDataContract(MetierRvMedical.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MetierRvMedical.CompositeType> GetDataUsingDataContractAsync(MetierRvMedical.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAgenda", ReplyAction="http://tempuri.org/IService1/AddAgendaResponse")]
        bool AddAgenda(MaterielRvMedical.Model.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAgenda", ReplyAction="http://tempuri.org/IService1/AddAgendaResponse")]
        System.Threading.Tasks.Task<bool> AddAgendaAsync(MaterielRvMedical.Model.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAgenda", ReplyAction="http://tempuri.org/IService1/UpdateAgendaResponse")]
        bool UpdateAgenda(MaterielRvMedical.Model.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAgenda", ReplyAction="http://tempuri.org/IService1/UpdateAgendaResponse")]
        System.Threading.Tasks.Task<bool> UpdateAgendaAsync(MaterielRvMedical.Model.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListAgenda", ReplyAction="http://tempuri.org/IService1/GetListAgendaResponse")]
        MaterielRvMedical.Model.Agenda[] GetListAgenda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListAgenda", ReplyAction="http://tempuri.org/IService1/GetListAgendaResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Agenda[]> GetListAgendaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMedecinById", ReplyAction="http://tempuri.org/IService1/GetMedecinByIdResponse")]
        MaterielRvMedical.Model.Medecin GetMedecinById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMedecinById", ReplyAction="http://tempuri.org/IService1/GetMedecinByIdResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Medecin> GetMedecinByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAgenda", ReplyAction="http://tempuri.org/IService1/DeleteAgendaResponse")]
        bool DeleteAgenda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAgenda", ReplyAction="http://tempuri.org/IService1/DeleteAgendaResponse")]
        System.Threading.Tasks.Task<bool> DeleteAgendaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAgendaById", ReplyAction="http://tempuri.org/IService1/GetAgendaByIdResponse")]
        MaterielRvMedical.Model.Agenda GetAgendaById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAgendaById", ReplyAction="http://tempuri.org/IService1/GetAgendaByIdResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Agenda> GetAgendaByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePatient", ReplyAction="http://tempuri.org/IService1/DeletePatientResponse")]
        bool DeletePatient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePatient", ReplyAction="http://tempuri.org/IService1/DeletePatientResponse")]
        System.Threading.Tasks.Task<bool> DeletePatientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPatientById", ReplyAction="http://tempuri.org/IService1/GetPatientByIdResponse")]
        MaterielRvMedical.Model.Patient GetPatientById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPatientById", ReplyAction="http://tempuri.org/IService1/GetPatientByIdResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Patient> GetPatientByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPatient", ReplyAction="http://tempuri.org/IService1/AddPatientResponse")]
        bool AddPatient(MaterielRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPatient", ReplyAction="http://tempuri.org/IService1/AddPatientResponse")]
        System.Threading.Tasks.Task<bool> AddPatientAsync(MaterielRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePatient", ReplyAction="http://tempuri.org/IService1/UpdatePatientResponse")]
        bool UpdatePatient(MaterielRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePatient", ReplyAction="http://tempuri.org/IService1/UpdatePatientResponse")]
        System.Threading.Tasks.Task<bool> UpdatePatientAsync(MaterielRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPatient", ReplyAction="http://tempuri.org/IService1/GetListPatientResponse")]
        MaterielRvMedical.Model.Patient[] GetListPatient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPatient", ReplyAction="http://tempuri.org/IService1/GetListPatientResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Patient[]> GetListPatientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMedecin", ReplyAction="http://tempuri.org/IService1/AddMedecinResponse")]
        bool AddMedecin(MaterielRvMedical.Model.Medecin medecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMedecin", ReplyAction="http://tempuri.org/IService1/AddMedecinResponse")]
        System.Threading.Tasks.Task<bool> AddMedecinAsync(MaterielRvMedical.Model.Medecin medecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMedecin", ReplyAction="http://tempuri.org/IService1/UpdateMedecinResponse")]
        bool UpdateMedecin(MaterielRvMedical.Model.Medecin medecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMedecin", ReplyAction="http://tempuri.org/IService1/UpdateMedecinResponse")]
        System.Threading.Tasks.Task<bool> UpdateMedecinAsync(MaterielRvMedical.Model.Medecin medecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListMedecin", ReplyAction="http://tempuri.org/IService1/GetListMedecinResponse")]
        MaterielRvMedical.Model.Medecin[] GetListMedecin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListMedecin", ReplyAction="http://tempuri.org/IService1/GetListMedecinResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Medecin[]> GetListMedecinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMedecin", ReplyAction="http://tempuri.org/IService1/DeleteMedecinResponse")]
        bool DeleteMedecin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMedecin", ReplyAction="http://tempuri.org/IService1/DeleteMedecinResponse")]
        System.Threading.Tasks.Task<bool> DeleteMedecinAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddRendezvous", ReplyAction="http://tempuri.org/IService1/AddRendezvousResponse")]
        bool AddRendezvous(MaterielRvMedical.Model.RendezVous rendezVous);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddRendezvous", ReplyAction="http://tempuri.org/IService1/AddRendezvousResponse")]
        System.Threading.Tasks.Task<bool> AddRendezvousAsync(MaterielRvMedical.Model.RendezVous rendezVous);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRendezvous", ReplyAction="http://tempuri.org/IService1/UpdateRendezvousResponse")]
        bool UpdateRendezvous(MaterielRvMedical.Model.RendezVous rendezVous);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRendezvous", ReplyAction="http://tempuri.org/IService1/UpdateRendezvousResponse")]
        System.Threading.Tasks.Task<bool> UpdateRendezvousAsync(MaterielRvMedical.Model.RendezVous rendezVous);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListRendezvous", ReplyAction="http://tempuri.org/IService1/GetListRendezvousResponse")]
        MaterielRvMedical.Model.RendezVous[] GetListRendezvous();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListRendezvous", ReplyAction="http://tempuri.org/IService1/GetListRendezvousResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.RendezVous[]> GetListRendezvousAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRendezvous", ReplyAction="http://tempuri.org/IService1/DeleteRendezvousResponse")]
        bool DeleteRendezvous(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRendezvous", ReplyAction="http://tempuri.org/IService1/DeleteRendezvousResponse")]
        System.Threading.Tasks.Task<bool> DeleteRendezvousAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCreneau", ReplyAction="http://tempuri.org/IService1/AddCreneauResponse")]
        bool AddCreneau(MaterielRvMedical.Model.Creneau creneau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCreneau", ReplyAction="http://tempuri.org/IService1/AddCreneauResponse")]
        System.Threading.Tasks.Task<bool> AddCreneauAsync(MaterielRvMedical.Model.Creneau creneau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCreneau", ReplyAction="http://tempuri.org/IService1/UpdateCreneauResponse")]
        bool UpdateCreneau(MaterielRvMedical.Model.Creneau creneau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCreneau", ReplyAction="http://tempuri.org/IService1/UpdateCreneauResponse")]
        System.Threading.Tasks.Task<bool> UpdateCreneauAsync(MaterielRvMedical.Model.Creneau creneau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListCreneau", ReplyAction="http://tempuri.org/IService1/GetListCreneauResponse")]
        MaterielRvMedical.Model.Creneau[] GetListCreneau();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListCreneau", ReplyAction="http://tempuri.org/IService1/GetListCreneauResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Creneau[]> GetListCreneauAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCreneau", ReplyAction="http://tempuri.org/IService1/DeleteCreneauResponse")]
        bool DeleteCreneau(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCreneau", ReplyAction="http://tempuri.org/IService1/DeleteCreneauResponse")]
        System.Threading.Tasks.Task<bool> DeleteCreneauAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRendezvousById", ReplyAction="http://tempuri.org/IService1/GetRendezvousByIdResponse")]
        MaterielRvMedical.Model.RendezVous GetRendezvousById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRendezvousById", ReplyAction="http://tempuri.org/IService1/GetRendezvousByIdResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.RendezVous> GetRendezvousByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCreneauById", ReplyAction="http://tempuri.org/IService1/GetCreneauByIdResponse")]
        MaterielRvMedical.Model.Creneau GetCreneauById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCreneauById", ReplyAction="http://tempuri.org/IService1/GetCreneauByIdResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Creneau> GetCreneauByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecialiteById", ReplyAction="http://tempuri.org/IService1/GetSpecialiteByIdResponse")]
        MaterielRvMedical.Model.Specialite GetSpecialiteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecialiteById", ReplyAction="http://tempuri.org/IService1/GetSpecialiteByIdResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Specialite> GetSpecialiteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllSpecialites", ReplyAction="http://tempuri.org/IService1/GetAllSpecialitesResponse")]
        MaterielRvMedical.Model.Specialite[] GetAllSpecialites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllSpecialites", ReplyAction="http://tempuri.org/IService1/GetAllSpecialitesResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Specialite[]> GetAllSpecialitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupeSanguinById", ReplyAction="http://tempuri.org/IService1/GetGroupeSanguinByIdResponse")]
        MaterielRvMedical.Model.GroupeSanguin GetGroupeSanguinById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGroupeSanguinById", ReplyAction="http://tempuri.org/IService1/GetGroupeSanguinByIdResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.GroupeSanguin> GetGroupeSanguinByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGroupesSanguins", ReplyAction="http://tempuri.org/IService1/GetAllGroupesSanguinsResponse")]
        MaterielRvMedical.Model.GroupeSanguin[] GetAllGroupesSanguins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGroupesSanguins", ReplyAction="http://tempuri.org/IService1/GetAllGroupesSanguinsResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.GroupeSanguin[]> GetAllGroupesSanguinsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUtilisateurByIdentifiant", ReplyAction="http://tempuri.org/IService1/GetUtilisateurByIdentifiantResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaterielRvMedical.Model.Admin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaterielRvMedical.Model.Medecin))]
        MaterielRvMedical.Model.Utilisateur GetUtilisateurByIdentifiant(string identifiant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUtilisateurByIdentifiant", ReplyAction="http://tempuri.org/IService1/GetUtilisateurByIdentifiantResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Utilisateur> GetUtilisateurByIdentifiantAsync(string identifiant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSoin", ReplyAction="http://tempuri.org/IService1/AddSoinResponse")]
        bool AddSoin(MaterielRvMedical.Model.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSoin", ReplyAction="http://tempuri.org/IService1/AddSoinResponse")]
        System.Threading.Tasks.Task<bool> AddSoinAsync(MaterielRvMedical.Model.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSoin", ReplyAction="http://tempuri.org/IService1/UpdateSoinResponse")]
        bool UpdateSoin(MaterielRvMedical.Model.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSoin", ReplyAction="http://tempuri.org/IService1/UpdateSoinResponse")]
        System.Threading.Tasks.Task<bool> UpdateSoinAsync(MaterielRvMedical.Model.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListSoin", ReplyAction="http://tempuri.org/IService1/GetListSoinResponse")]
        MaterielRvMedical.Model.Soin[] GetListSoin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListSoin", ReplyAction="http://tempuri.org/IService1/GetListSoinResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Soin[]> GetListSoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSoinById", ReplyAction="http://tempuri.org/IService1/GetSoinByIdResponse")]
        MaterielRvMedical.Model.Soin GetSoinById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSoinById", ReplyAction="http://tempuri.org/IService1/GetSoinByIdResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Soin> GetSoinByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSoin", ReplyAction="http://tempuri.org/IService1/DeleteSoinResponse")]
        bool DeleteSoin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSoin", ReplyAction="http://tempuri.org/IService1/DeleteSoinResponse")]
        System.Threading.Tasks.Task<bool> DeleteSoinAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoleByCode", ReplyAction="http://tempuri.org/IService1/GetRoleByCodeResponse")]
        MaterielRvMedical.Model.Role GetRoleByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoleByCode", ReplyAction="http://tempuri.org/IService1/GetRoleByCodeResponse")]
        System.Threading.Tasks.Task<MaterielRvMedical.Model.Role> GetRoleByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountAdmins", ReplyAction="http://tempuri.org/IService1/CountAdminsResponse")]
        int CountAdmins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountAdmins", ReplyAction="http://tempuri.org/IService1/CountAdminsResponse")]
        System.Threading.Tasks.Task<int> CountAdminsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAdmin", ReplyAction="http://tempuri.org/IService1/AddAdminResponse")]
        bool AddAdmin(MaterielRvMedical.Model.Admin admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAdmin", ReplyAction="http://tempuri.org/IService1/AddAdminResponse")]
        System.Threading.Tasks.Task<bool> AddAdminAsync(MaterielRvMedical.Model.Admin admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddError", ReplyAction="http://tempuri.org/IService1/AddErrorResponse")]
        bool AddError(MaterielRvMedical.Model.Td_Erreur erreur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddError", ReplyAction="http://tempuri.org/IService1/AddErrorResponse")]
        System.Threading.Tasks.Task<bool> AddErrorAsync(MaterielRvMedical.Model.Td_Erreur erreur);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AppGroupe2.ServiceMetier.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AppGroupe2.ServiceMetier.IService1>, AppGroupe2.ServiceMetier.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MetierRvMedical.CompositeType GetDataUsingDataContract(MetierRvMedical.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MetierRvMedical.CompositeType> GetDataUsingDataContractAsync(MetierRvMedical.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool AddAgenda(MaterielRvMedical.Model.Agenda agenda) {
            return base.Channel.AddAgenda(agenda);
        }
        
        public System.Threading.Tasks.Task<bool> AddAgendaAsync(MaterielRvMedical.Model.Agenda agenda) {
            return base.Channel.AddAgendaAsync(agenda);
        }
        
        public bool UpdateAgenda(MaterielRvMedical.Model.Agenda agenda) {
            return base.Channel.UpdateAgenda(agenda);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAgendaAsync(MaterielRvMedical.Model.Agenda agenda) {
            return base.Channel.UpdateAgendaAsync(agenda);
        }
        
        public MaterielRvMedical.Model.Agenda[] GetListAgenda() {
            return base.Channel.GetListAgenda();
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Agenda[]> GetListAgendaAsync() {
            return base.Channel.GetListAgendaAsync();
        }
        
        public MaterielRvMedical.Model.Medecin GetMedecinById(int id) {
            return base.Channel.GetMedecinById(id);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Medecin> GetMedecinByIdAsync(int id) {
            return base.Channel.GetMedecinByIdAsync(id);
        }
        
        public bool DeleteAgenda(int id) {
            return base.Channel.DeleteAgenda(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAgendaAsync(int id) {
            return base.Channel.DeleteAgendaAsync(id);
        }
        
        public MaterielRvMedical.Model.Agenda GetAgendaById(int id) {
            return base.Channel.GetAgendaById(id);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Agenda> GetAgendaByIdAsync(int id) {
            return base.Channel.GetAgendaByIdAsync(id);
        }
        
        public bool DeletePatient(int id) {
            return base.Channel.DeletePatient(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePatientAsync(int id) {
            return base.Channel.DeletePatientAsync(id);
        }
        
        public MaterielRvMedical.Model.Patient GetPatientById(int id) {
            return base.Channel.GetPatientById(id);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Patient> GetPatientByIdAsync(int id) {
            return base.Channel.GetPatientByIdAsync(id);
        }
        
        public bool AddPatient(MaterielRvMedical.Model.Patient patient) {
            return base.Channel.AddPatient(patient);
        }
        
        public System.Threading.Tasks.Task<bool> AddPatientAsync(MaterielRvMedical.Model.Patient patient) {
            return base.Channel.AddPatientAsync(patient);
        }
        
        public bool UpdatePatient(MaterielRvMedical.Model.Patient patient) {
            return base.Channel.UpdatePatient(patient);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePatientAsync(MaterielRvMedical.Model.Patient patient) {
            return base.Channel.UpdatePatientAsync(patient);
        }
        
        public MaterielRvMedical.Model.Patient[] GetListPatient() {
            return base.Channel.GetListPatient();
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Patient[]> GetListPatientAsync() {
            return base.Channel.GetListPatientAsync();
        }
        
        public bool AddMedecin(MaterielRvMedical.Model.Medecin medecin) {
            return base.Channel.AddMedecin(medecin);
        }
        
        public System.Threading.Tasks.Task<bool> AddMedecinAsync(MaterielRvMedical.Model.Medecin medecin) {
            return base.Channel.AddMedecinAsync(medecin);
        }
        
        public bool UpdateMedecin(MaterielRvMedical.Model.Medecin medecin) {
            return base.Channel.UpdateMedecin(medecin);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMedecinAsync(MaterielRvMedical.Model.Medecin medecin) {
            return base.Channel.UpdateMedecinAsync(medecin);
        }
        
        public MaterielRvMedical.Model.Medecin[] GetListMedecin() {
            return base.Channel.GetListMedecin();
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Medecin[]> GetListMedecinAsync() {
            return base.Channel.GetListMedecinAsync();
        }
        
        public bool DeleteMedecin(int id) {
            return base.Channel.DeleteMedecin(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMedecinAsync(int id) {
            return base.Channel.DeleteMedecinAsync(id);
        }
        
        public bool AddRendezvous(MaterielRvMedical.Model.RendezVous rendezVous) {
            return base.Channel.AddRendezvous(rendezVous);
        }
        
        public System.Threading.Tasks.Task<bool> AddRendezvousAsync(MaterielRvMedical.Model.RendezVous rendezVous) {
            return base.Channel.AddRendezvousAsync(rendezVous);
        }
        
        public bool UpdateRendezvous(MaterielRvMedical.Model.RendezVous rendezVous) {
            return base.Channel.UpdateRendezvous(rendezVous);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRendezvousAsync(MaterielRvMedical.Model.RendezVous rendezVous) {
            return base.Channel.UpdateRendezvousAsync(rendezVous);
        }
        
        public MaterielRvMedical.Model.RendezVous[] GetListRendezvous() {
            return base.Channel.GetListRendezvous();
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.RendezVous[]> GetListRendezvousAsync() {
            return base.Channel.GetListRendezvousAsync();
        }
        
        public bool DeleteRendezvous(int id) {
            return base.Channel.DeleteRendezvous(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRendezvousAsync(int id) {
            return base.Channel.DeleteRendezvousAsync(id);
        }
        
        public bool AddCreneau(MaterielRvMedical.Model.Creneau creneau) {
            return base.Channel.AddCreneau(creneau);
        }
        
        public System.Threading.Tasks.Task<bool> AddCreneauAsync(MaterielRvMedical.Model.Creneau creneau) {
            return base.Channel.AddCreneauAsync(creneau);
        }
        
        public bool UpdateCreneau(MaterielRvMedical.Model.Creneau creneau) {
            return base.Channel.UpdateCreneau(creneau);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCreneauAsync(MaterielRvMedical.Model.Creneau creneau) {
            return base.Channel.UpdateCreneauAsync(creneau);
        }
        
        public MaterielRvMedical.Model.Creneau[] GetListCreneau() {
            return base.Channel.GetListCreneau();
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Creneau[]> GetListCreneauAsync() {
            return base.Channel.GetListCreneauAsync();
        }
        
        public bool DeleteCreneau(int id) {
            return base.Channel.DeleteCreneau(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCreneauAsync(int id) {
            return base.Channel.DeleteCreneauAsync(id);
        }
        
        public MaterielRvMedical.Model.RendezVous GetRendezvousById(int id) {
            return base.Channel.GetRendezvousById(id);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.RendezVous> GetRendezvousByIdAsync(int id) {
            return base.Channel.GetRendezvousByIdAsync(id);
        }
        
        public MaterielRvMedical.Model.Creneau GetCreneauById(int id) {
            return base.Channel.GetCreneauById(id);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Creneau> GetCreneauByIdAsync(int id) {
            return base.Channel.GetCreneauByIdAsync(id);
        }
        
        public MaterielRvMedical.Model.Specialite GetSpecialiteById(int id) {
            return base.Channel.GetSpecialiteById(id);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Specialite> GetSpecialiteByIdAsync(int id) {
            return base.Channel.GetSpecialiteByIdAsync(id);
        }
        
        public MaterielRvMedical.Model.Specialite[] GetAllSpecialites() {
            return base.Channel.GetAllSpecialites();
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Specialite[]> GetAllSpecialitesAsync() {
            return base.Channel.GetAllSpecialitesAsync();
        }
        
        public MaterielRvMedical.Model.GroupeSanguin GetGroupeSanguinById(int id) {
            return base.Channel.GetGroupeSanguinById(id);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.GroupeSanguin> GetGroupeSanguinByIdAsync(int id) {
            return base.Channel.GetGroupeSanguinByIdAsync(id);
        }
        
        public MaterielRvMedical.Model.GroupeSanguin[] GetAllGroupesSanguins() {
            return base.Channel.GetAllGroupesSanguins();
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.GroupeSanguin[]> GetAllGroupesSanguinsAsync() {
            return base.Channel.GetAllGroupesSanguinsAsync();
        }
        
        public MaterielRvMedical.Model.Utilisateur GetUtilisateurByIdentifiant(string identifiant) {
            return base.Channel.GetUtilisateurByIdentifiant(identifiant);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Utilisateur> GetUtilisateurByIdentifiantAsync(string identifiant) {
            return base.Channel.GetUtilisateurByIdentifiantAsync(identifiant);
        }
        
        public bool AddSoin(MaterielRvMedical.Model.Soin soin) {
            return base.Channel.AddSoin(soin);
        }
        
        public System.Threading.Tasks.Task<bool> AddSoinAsync(MaterielRvMedical.Model.Soin soin) {
            return base.Channel.AddSoinAsync(soin);
        }
        
        public bool UpdateSoin(MaterielRvMedical.Model.Soin soin) {
            return base.Channel.UpdateSoin(soin);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSoinAsync(MaterielRvMedical.Model.Soin soin) {
            return base.Channel.UpdateSoinAsync(soin);
        }
        
        public MaterielRvMedical.Model.Soin[] GetListSoin() {
            return base.Channel.GetListSoin();
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Soin[]> GetListSoinAsync() {
            return base.Channel.GetListSoinAsync();
        }
        
        public MaterielRvMedical.Model.Soin GetSoinById(int id) {
            return base.Channel.GetSoinById(id);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Soin> GetSoinByIdAsync(int id) {
            return base.Channel.GetSoinByIdAsync(id);
        }
        
        public bool DeleteSoin(int id) {
            return base.Channel.DeleteSoin(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSoinAsync(int id) {
            return base.Channel.DeleteSoinAsync(id);
        }
        
        public MaterielRvMedical.Model.Role GetRoleByCode(string code) {
            return base.Channel.GetRoleByCode(code);
        }
        
        public System.Threading.Tasks.Task<MaterielRvMedical.Model.Role> GetRoleByCodeAsync(string code) {
            return base.Channel.GetRoleByCodeAsync(code);
        }
        
        public int CountAdmins() {
            return base.Channel.CountAdmins();
        }
        
        public System.Threading.Tasks.Task<int> CountAdminsAsync() {
            return base.Channel.CountAdminsAsync();
        }
        
        public bool AddAdmin(MaterielRvMedical.Model.Admin admin) {
            return base.Channel.AddAdmin(admin);
        }
        
        public System.Threading.Tasks.Task<bool> AddAdminAsync(MaterielRvMedical.Model.Admin admin) {
            return base.Channel.AddAdminAsync(admin);
        }
        
        public bool AddError(MaterielRvMedical.Model.Td_Erreur erreur) {
            return base.Channel.AddError(erreur);
        }
        
        public System.Threading.Tasks.Task<bool> AddErrorAsync(MaterielRvMedical.Model.Td_Erreur erreur) {
            return base.Channel.AddErrorAsync(erreur);
        }
    }
}
